joblistings/urls.py
# # urls.py
# from django.urls import path
# from .views import JobPageList, JobImportView, ExcelUploadView

# urlpatterns = [
#     path('jobs/', JobPageList.as_view(), name='api_jobs'),
#     path('import-jobs/', JobImportView.as_view(), name='job_import'),
#     path('upload_excel/', ExcelUploadView.as_view(), name='upload_excel'),


# ]
from django.urls import path, include
from rest_framework.routers import DefaultRouter
from .views import post_indeed_jobs_to_google, fetch_indeed_jobs #, job_search
from .views import JobPageViewSet, JobImportView, ExcelUploadView, JobPageAddViewSet

from django.conf import settings
router = DefaultRouter()
router.register(r'jobs', JobPageViewSet, basename='jobpage')
router.register(r'add_jobs', JobPageAddViewSet, basename='jobpageadd')

urlpatterns = [
        path('', include(router.urls)),
#    path('job_search/', job_search, name='job_search'),
    path('job_list/', post_indeed_jobs_to_google, name='job_list'),
    path('job_fetch/', fetch_indeed_jobs, name='job_fetch'),

]

# Conditionally add debug toolbar routes in development mode
if settings.DEBUG:
    import debug_toolbar
    urlpatterns = [
        path('__debug__/', include(debug_toolbar.urls)),
    ] + urlpatterns

users/urls.py
from rest_framework import routers
from .views import UserRegister, MyTokenObtainPairView, VerifyTokenView, TestView, UserRoleView
from django.urls import path
from rest_framework_simplejwt.views import (
    TokenRefreshView,
)


urlpatterns = [
    path('register/', UserRegister.as_view(), name='register'),
    path('login/', MyTokenObtainPairView.as_view(), name='login'),
    path('refresh/', TokenRefreshView.as_view(), name='token_refresh'),
    path('verify/', VerifyTokenView.as_view(), name='token_verify'),
    path('admin/create_user/', UserRegister.as_view(), name='admin-create-user'),
    path('test/', TestView.as_view(), name='test'),
    path('role/', UserRoleView.as_view(), name='role'),
    

]

joblistings/models.py
from django.db import models
from wagtail.models import Page
from wagtail.admin.panels import FieldPanel, MultiFieldPanel, InlinePanel
from wagtail.fields import RichTextField
from modelcluster.fields import ParentalKey
from modelcluster.models import ClusterableModel

class City(models.Model):
    name = models.CharField(max_length=255, unique=True)

    def __str__(self):
        return self.name

class Company(models.Model):
    name = models.CharField(max_length=255, unique=True)

    def __str__(self):
        return self.name

class JobIndexPage(Page):
    subpage_types = ['JobPage']
    max_count = 1

    content_panels = Page.content_panels + [
        # Add panels for any fields you define on your index page
    ]
    template = "joblistings/job_index_page.html"

class ContactPerson(models.Model):
    job_page = ParentalKey('JobPage', related_name='contact_persons', on_delete=models.CASCADE)
    name = models.CharField(max_length=255, blank=True, null=True)
    linkedin = models.URLField(blank=True, null=True)
    email = models.EmailField(blank=True, null=True)

    panels = [
        FieldPanel('name'),
        FieldPanel('linkedin'),
        FieldPanel('email'),
    ]
class Industry(models.Model):
    name = models.CharField(max_length=255, unique=True)

    def __str__(self):
        return self.name

class Category(models.Model):
    name = models.CharField(max_length=255, unique=True)

    def __str__(self):
        return self.name

class ContactIntern(models.Model):
    job_page = ParentalKey('JobPage', related_name='contact_interns', on_delete=models.CASCADE)
    name = models.CharField(max_length=255, blank=True, null=True)
    linkedin = models.URLField(blank=True, null=True)
    email = models.EmailField(blank=True, null=True)

    panels = [
        FieldPanel('name'),
        FieldPanel('linkedin'),
        FieldPanel('email'),
    ]
class Currency(models.Model):
    code = models.CharField(max_length=3, unique=True)
    name = models.CharField(max_length=255)

    def __str__(self):
        return f"{self.code} - {self.name}"

from django.db import models
from wagtail.models import Page
from wagtail.admin.panels import FieldPanel, MultiFieldPanel, InlinePanel
from wagtail.fields import RichTextField
from modelcluster.fields import ParentalKey
from modelcluster.models import ClusterableModel

class City(models.Model):
    name = models.CharField(max_length=255, unique=True)

    def __str__(self):
        return self.name

class Company(models.Model):
    name = models.CharField(max_length=255, unique=True)

    def __str__(self):
        return self.name

class JobIndexPage(Page):
    subpage_types = ['JobPage']
    max_count = 1

    content_panels = Page.content_panels + [
        # Add panels for any fields you define on your index page
    ]
    template = "joblistings/job_index_page.html"

class ContactPerson(models.Model):
    job_page = ParentalKey('JobPage', related_name='contact_persons', on_delete=models.CASCADE)
    name = models.CharField(max_length=255, blank=True, null=True)
    linkedin = models.URLField(blank=True, null=True)
    email = models.EmailField(blank=True, null=True)

    panels = [
        FieldPanel('name'),
        FieldPanel('linkedin'),
        FieldPanel('email'),
    ]
class CoddingLanguages(models.Model):
    name = models.CharField(max_length=255, unique=True)

    def __str__(self):
        return self.name
class Industry(models.Model):
    name = models.CharField(max_length=255, unique=True)

    def __str__(self):
        return self.name

class Category(models.Model):
    name = models.CharField(max_length=255, unique=True)

    def __str__(self):
        return self.name


class Currency(models.Model):
    code = models.CharField(max_length=3, unique=True)

    def __str__(self):
        return f"{self.code} "
class Languages(models.Model):
    name = models.CharField(max_length=255, unique=True)

    def __str__(self):
        return self.name

class JobPage(Page, ClusterableModel):
    parent_page_types = ['JobIndexPage']
    subpage_types = []

    JOB_TYPE_CHOICES = [
        ('remote', 'Remote'),
        ('full time', 'Full Time'),
        ('part time', 'Part Time'),
    ]

    MONTH_CHOICES = [
        ('01', 'January'),
        ('02', 'February'),
        ('03', 'March'),
        ('04', 'April'),
        ('05', 'May'),
        ('06', 'June'),
        ('07', 'July'),
        ('08', 'August'),
        ('09', 'September'),
        ('10', 'October'),
        ('11', 'November'),
        ('12', 'December'),
    ]

    industry = models.ForeignKey(Industry, on_delete=models.SET_NULL, null=True, blank=True)
    categories = models.ForeignKey(Category, on_delete=models.SET_NULL, null=True, blank=True)
    job_title = models.CharField(max_length=255, blank=True)
    company_name = models.ForeignKey(Company, on_delete=models.SET_NULL, null=True, blank=True)
    location = models.ForeignKey(City, on_delete=models.SET_NULL, null=True, blank=True)
    contract_type = models.CharField(max_length=255, choices=JOB_TYPE_CHOICES, blank=True)
    duration = models.IntegerField(blank=True, null=True, help_text="Duration in months")
    month = models.CharField(max_length=2, choices=MONTH_CHOICES, blank=True, null=True)
    job_description = RichTextField(blank=True)
    notes_feedbacks = RichTextField(blank=True)
    language_requirements = models.ManyToManyField(Languages, blank=True)
    expected_salary = models.FloatField(blank=True, null=True)
    currency = models.ForeignKey(Currency, on_delete=models.SET_NULL, null=True, blank=True, related_name='jobs')
    new_currency_code = models.CharField(max_length=3, blank=True, help_text="Currency code (e.g., USD)")
    coding_languages = models.ManyToManyField(CoddingLanguages, blank=True)
    asset_class = models.CharField(max_length=255, blank=True)
    interview_report_link = models.URLField(blank=True)
    new_company_name = models.CharField(max_length=255, blank=True, help_text="Add a new company if it's not listed")
    new_city_name = models.CharField(max_length=255, blank=True, help_text="Add a new city if it's not listed")
    new_industry_name = models.CharField(max_length=255, blank=True, help_text="Add a new industry if it's not listed")
    new_category_name = models.CharField(max_length=255, blank=True, help_text="Add a new category if it's not listed")
    new_language_name = models.CharField(max_length=255, blank=True, help_text="Add a new language if it's not listed")
    content_panels = Page.content_panels + [
        MultiFieldPanel([
            FieldPanel('industry'),
            FieldPanel('new_industry_name'),
            FieldPanel('categories'),
            FieldPanel('new_category_name'),
            FieldPanel('job_title'),
            FieldPanel('company_name'),
            FieldPanel('new_company_name'),
            FieldPanel('location'),
            FieldPanel('new_city_name'),
            FieldPanel('contract_type'),
            FieldPanel('duration'),
            FieldPanel('month'),
            FieldPanel('job_description'),
            FieldPanel('notes_feedbacks'),
            FieldPanel('language_requirements'),
            FieldPanel('new_language_name'),
            FieldPanel('expected_salary'),
            FieldPanel('currency'),
            FieldPanel('new_currency_code'),

            FieldPanel('coding_languages'),
            FieldPanel('asset_class'),
            FieldPanel('interview_report_link'),
        ], heading="Job Details"),
        MultiFieldPanel([
            InlinePanel('contact_persons', label="Contact Persons"),
        ], heading="Contact Persons"),
        MultiFieldPanel([
            InlinePanel('contact_interns', label="Contact interns"),
        ], heading="Contact interns"),
    ]

    template = "joblistings/job_page.html"

    def save(self, *args, **kwargs):
        super().save(*args, **kwargs)  # Call save first to ensure the object exists if it's new

        if self.new_company_name:
            new_company, created = Company.objects.get_or_create(name=self.new_company_name)
            self.company_name = new_company
            self.new_company_name = ''  # Clear the field after saving

        if self.new_city_name:
            new_city, created = City.objects.get_or_create(name=self.new_city_name)
            self.location = new_city
            self.new_city_name = ''  # Clear the field after saving

        if self.new_language_name:
            new_language, created = Languages.objects.get_or_create(name=self.new_language_name)
            # Use set for ManyToMany field to replace all existing entries
            self.language_requirements.set([new_language])
            self.new_language_name = ''

        if self.new_industry_name:
            new_industry, created = Industry.objects.get_or_create(name=self.new_industry_name)
            self.industry = new_industry
            self.new_industry_name = ''  # Clear the field after saving

        if self.new_category_name:
            new_category, created = Category.objects.get_or_create(name=self.new_category_name)
            self.categories = new_category
            self.new_category_name = ''  # Clear the field after saving

        if self.new_currency_code:
            new_currency, created = Currency.objects.get_or_create(code=self.new_currency_code)
            self.currency = new_currency
            self.new_currency_code = ''

        super().save(*args, **kwargs)  # Save again to update any changed relations

joblistings/forms.py
# forms.py in your wagtail app
from django import forms
from .models import City, Company, JobPage

class JobImportForm(forms.Form):
    excel_file = forms.FileField()

class JobPageForm(forms.ModelForm):
    new_city = forms.CharField(required=False, help_text="Enter a new city if it doesn't exist in the list.")
    new_company = forms.CharField(required=False, help_text="Enter a new company if it doesn't exist in the list.")

    class Meta:
        model = JobPage
        fields = '__all__'

    def save(self, commit=True):
        new_city = self.cleaned_data.get('new_city')
        new_company = self.cleaned_data.get('new_company')

        if new_city:
            city, created = City.objects.get_or_create(name=new_city)
            self.instance.location = city

        if new_company:
            company, created = Company.objects.get_or_create(name=new_company)
            self.instance.company_name = company

        return super().save(commit=commit)

joblistings/templates/joblistings/add_company.html
<!-- templates/joblistings/add_company.html -->
{% extends "wagtailadmin/base.html" %}
{% load wagtailadmin_tags %}

{% block body_class %}full-width{% endblock %}

{% block content %}
    <div class="content">
        <h1>Add a new Company</h1>
        <form method="post">{% csrf_token %}
            {{ form.as_p }}
            <button type="submit" class="button">Add Company</button>
        </form>
    </div>
{% endblock %}

joblistings/templates/joblistings/job_index_page.html
<!-- joblistings/job_page.html -->
{% load wagtailcore_tags %}
<!DOCTYPE html>
<html>
<head>
    <title>{{ page.title }}</title>
</head>
<body>
    <h1>{{ page.title }}</h1>
    <p><strong>Industry:</strong> {{ page.industry }}</p>
    <p><strong>Categories:</strong> {{ page.categories }}</p>
    <p><strong>Job Title:</strong> {{ page.job_title }}</p>
    <p><strong>Company:</strong> {{ page.company_name }}</p>
    <p><strong>Location:</strong> {{ page.location }}</p>
    <p><strong>Contract Type:</strong> {{ page.get_contract_type_display }}</p>
    <p><strong>Duration:</strong> {{ page.duration }} months</p>
    <p><strong>Month:</strong> {{ page.get_month_display }}</p>
    <p><strong>Job Description:</strong> {{ page.job_description|richtext }}</p>
    <p><strong>Notes/Feedbacks:</strong> {{ page.notes_feedbacks|richtext }}</p>
    <p><strong>Language Requirements:</strong> {{ page.language_requirements }}</p>
    <p><strong>Expected Salary:</strong> {{ page.expected_salary }} {{ page.currency.code }}</p>
    <p><strong>Coding Languages:</strong> {{ page.coding_languages }}</p>
    <p><strong>Asset Class:</strong> {{ page.asset_class }}</p>
    <p><strong>Interview Report Link:</strong> <a href="{{ page.interview_report_link }}">{{ page.interview_report_link }}</a></p>
    <h2>Contact Persons</h2>
    <ul>
        {% for contact in page.contact_persons.all %}
        <li>{{ contact.name }} - <a href="{{ contact.linkedin }}">LinkedIn</a> - <a href="mailto:{{ contact.email }}">{{ contact.email }}</a></li>
        {% endfor %}
    </ul>
</body>
</html>

joblistings/templates/joblistings/job_page.html
<!-- joblistings/job_page.html -->
{% load wagtailcore_tags %}
<!DOCTYPE html>
<html>
<head>
    <title>{{ page.title }}</title>
</head>
<body>
    <h1>{{ page.title }}</h1>
    <p><strong>Industry:</strong> {{ page.industry }}</p>
    <p><strong>Categories:</strong> {{ page.categories }}</p>
    <p><strong>Job Title:</strong> {{ page.job_title }}</p>
    <p><strong>Company:</strong> {{ page.company_name }}</p>
    <p><strong>Location:</strong> {{ page.location }}</p>
    <p><strong>Contract Type:</strong> {{ page.get_contract_type_display }}</p>
    <p><strong>Duration:</strong> {{ page.duration }} months</p>
    <p><strong>Month:</strong> {{ page.get_month_display }}</p>
    <p><strong>Job Description:</strong> {{ page.job_description|richtext }}</p>
    <p><strong>Notes/Feedbacks:</strong> {{ page.notes_feedbacks|richtext }}</p>
    <p><strong>Language Requirements:</strong> {{ page.language_requirements }}</p>
    <p><strong>Expected Salary:</strong> {{ page.expected_salary }} {{ page.currency.code }}</p>
    <p><strong>Coding Languages:</strong> {{ page.coding_languages }}</p>
    <p><strong>Asset Class:</strong> {{ page.asset_class }}</p>
    <p><strong>Interview Report Link:</strong> <a href="{{ page.interview_report_link }}">{{ page.interview_report_link }}</a></p>
    <h2>Contact Persons</h2>
    <ul>
        {% for contact in page.contact_persons.all %}
        <li>{{ contact.name }} - <a href="{{ contact.linkedin }}">LinkedIn</a> - <a href="mailto:{{ contact.email }}">{{ contact.email }}</a></li>
        {% endfor %}
    </ul>
</body>
</html>

joblistings/templates/joblistings/upload.html
{% extends "wagtailadmin/admin_base.html" %}
{% load i18n wagtailadmin_tags %}

{% block titletag %}{% trans "Upload Jobs" %}{% endblock %}

{% block bodyclass %}finance-jobs-upload{% endblock %}

{% block content %}
    <header class="nice-padding has-form-actions">
        <h1 class="h2">{% trans 'Upload Jobs' %}</h1>
    </header>
    <div class="nice-padding">
        <form action="{% url 'finance_jobs:upload_jobs' %}" method="post" enctype="multipart/form-data">
            {% csrf_token %}
            {{ form.as_p }}
            <ul class="actions">
                <li><button type="submit" class="button">{% trans 'Upload' %}</button></li>
            </ul>
        </form>
    </div>
{% endblock %}